[package]
name = "nhls"
version = "0.1.0"
edition = "2021"

[dependencies]
colorous = "1.0.14"
fftw = { path = "/Users/russell/projects/rust/fftw3-rs/fftw", features = ["system"] }

image = "0.25.2"
num = "0.4.3"
num-traits = "0.2.19"
rayon = "1.10.0"

[dev-dependencies]
float-cmp = "0.10.0"

